import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
	return (
		<div className="bg-black text-purple-300 min-h-screen">
			<Head>
				<title>Ecommerce Store</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<h2>Ecommerce Store</h2>
		</div>
	);
};

export default Home;
